# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 330, 81, 31))
        font = QFont()
        font.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        self.label.setFont(font)
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(74, 23, 133, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(13, 23, 55, 17))
        self.label_2.setFont(font)
        self.LookUp = QPushButton(self.centralwidget)
        self.LookUp.setObjectName(u"LookUp")
        self.LookUp.setGeometry(QRect(214, 22, 75, 25))
        self.LookUp.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(42, 83, 47, 17))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(42, 106, 27, 17))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(42, 152, 27, 17))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(42, 175, 27, 17))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(42, 198, 27, 17))
        self.label_7.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(11, 54, 75, 17))
        self.label_9.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(350, 60, 101, 16))
        self.label_10.setFont(font)
        self.VideoDownload = QPushButton(self.centralwidget)
        self.VideoDownload.setObjectName(u"VideoDownload")
        self.VideoDownload.setGeometry(QRect(381, 81, 75, 25))
        self.VideoDownload.setFont(font)
        self.CoverDownload = QPushButton(self.centralwidget)
        self.CoverDownload.setObjectName(u"CoverDownload")
        self.CoverDownload.setGeometry(QRect(381, 112, 75, 25))
        self.CoverDownload.setFont(font)
        self.BarrageDownload = QPushButton(self.centralwidget)
        self.BarrageDownload.setObjectName(u"BarrageDownload")
        self.BarrageDownload.setGeometry(QRect(381, 143, 76, 25))
        self.BarrageDownload.setFont(font)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(42, 221, 31, 17))
        self.label_11.setFont(font)
        self.AV = QLabel(self.centralwidget)
        self.AV.setObjectName(u"AV")
        self.AV.setGeometry(QRect(95, 83, 221, 16))
        self.AV.setFont(font)
        self.Title = QLabel(self.centralwidget)
        self.Title.setObjectName(u"Title")
        self.Title.setGeometry(QRect(95, 106, 231, 16))
        self.Title.setFont(font)
        self.Play = QLabel(self.centralwidget)
        self.Play.setObjectName(u"Play")
        self.Play.setGeometry(QRect(95, 129, 241, 16))
        self.Play.setFont(font)
        self.Likes = QLabel(self.centralwidget)
        self.Likes.setObjectName(u"Likes")
        self.Likes.setGeometry(QRect(95, 152, 261, 16))
        self.Likes.setFont(font)
        self.Coins = QLabel(self.centralwidget)
        self.Coins.setObjectName(u"Coins")
        self.Coins.setGeometry(QRect(95, 175, 261, 16))
        self.Coins.setFont(font)
        self.Collection = QLabel(self.centralwidget)
        self.Collection.setObjectName(u"Collection")
        self.Collection.setGeometry(QRect(95, 198, 261, 16))
        self.Collection.setFont(font)
        self.Uploder = QLabel(self.centralwidget)
        self.Uploder.setObjectName(u"Uploder")
        self.Uploder.setGeometry(QRect(95, 221, 271, 16))
        self.Uploder.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(42, 129, 27, 17))
        self.label_8.setFont(font)
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 360, 761, 181))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(666, 312, 75, 25))
        self.pushButton.setFont(font)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(42, 312, 75, 17))
        self.label_12.setFont(font)
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(123, 314, 521, 20))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(680, 0, 121, 20))
        self.label_13.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8f93\u51fa:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165BV\u53f7:", None))
        self.LookUp.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"BV\u8f6cAV:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u6807\u9898:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u8d5e:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u6295\u5e01:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u6536\u85cf:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u57fa\u672c\u4fe1\u606f:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u76f8\u5173\u4e0b\u8f7d:", None))
        self.VideoDownload.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u4e0b\u8f7d", None))
        self.CoverDownload.setText(QCoreApplication.translate("MainWindow", u"\u5c01\u9762\u4e0b\u8f7d", None))
        self.BarrageDownload.setText(QCoreApplication.translate("MainWindow", u"xml\u5f39\u5e55\u4e0b\u8f7d", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"UP\u4e3b:", None))
        self.AV.setText("")
        self.Title.setText("")
        self.Play.setText("")
        self.Likes.setText("")
        self.Coins.setText("")
        self.Collection.setText("")
        self.Uploder.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u64ad\u653e:", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u4fdd\u5b58\u8def\u5f84:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"by \u5343\u91cc\u626f\u6de1 2022", None))
    # retranslateUi

